# Generated by Django 2.2.16 on 2020-10-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='问题描述', max_length=200, verbose_name='问题描述')),
                ('pub_date', models.DateTimeField(help_text='发布时间', verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='选项描述', max_length=200, verbose_name='选项描述')),
                ('votes', models.IntegerField(default=0, help_text='当前得票数', verbose_name='当前得票数')),
                ('question', models.ForeignKey(help_text='所属问题', on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='所属问题')),
            ],
        ),
    ]
